### ISSUE TITLE
Training result

### ISSUE THREAD

**Issue by huytuong010101** [xml94/PlantCLEF2022#2]
Thank you for great repository,
Can you share the result of your training? Accuracy, loss, log,...

**Comment by xml94** [comment]
Hi, thank you for your interest.

Sorry to reply you late.

I checked my results. I can not find all logs now. Here I give the logs from 50 to 100 epoch.
By the way, I use part of training dataset as the validation dataset (test_acc below).

{"train_lr": 0.0005335122050743356, "train_loss": 4.495324867813847, "test_loss": 0.4541961507192974, "test_acc1": 92.53281843936881, "test_acc5": 98.51330345991174, "epoch": 50, "n_parameters": 385301632}
{"train_lr": 0.0005170158652777887, "train_loss": 4.471077668872582, "test_loss": 0.4114452936247327, "test_acc1": 92.73015410411362, "test_acc5": 98.57250415939076, "epoch": 51, "n_parameters": 385301632}
{"train_lr": 0.0005005014656250234, "train_loss": 4.455432934210777, "test_loss": 0.4314416221190293, "test_acc1": 93.06714270124077, "test_acc5": 98.65295639185399, "epoch": 52, "n_parameters": 385301632}
{"train_lr": 0.0005335122050743356, "train_loss": 4.49533496481264, "test_loss": 0.4578178479468628, "test_acc1": 92.53615796600609, "test_acc5": 98.51330345991174, "epoch": 50, "n_parameters": 385301632}
{"train_lr": 0.0005170158652777887, "train_loss": 4.471119584005713, "test_loss": 0.41190216618806424, "test_acc1": 92.72560020431582, "test_acc5": 98.56764666610017, "epoch": 51, "n_parameters": 385301632}
{"train_lr": 0.0005005014656250234, "train_loss": 4.455441215571274, "test_loss": 0.4319381663458539, "test_acc1": 93.03374743477534, "test_acc5": 98.6496168652167, "epoch": 52, "n_parameters": 385301632}
{"train_lr": 0.00048398706436963713, "train_loss": 4.442898375429803, "test_loss": 0.4191775405309116, "test_acc1": 93.19343752705082, "test_acc5": 98.65143842536281, "epoch": 53, "n_parameters": 385301632}
{"train_lr": 0.0004674907197669084, "train_loss": 4.413441716703052, "test_loss": 0.41524512187752183, "test_acc1": 93.50249553766444, "test_acc5": 98.74767751118257, "epoch": 54, "n_parameters": 385301632}
{"train_lr": 0.00045103047032747125, "train_loss": 4.3998434170098815, "test_loss": 0.40826531844076114, "test_acc1": 93.54955250391701, "test_acc5": 98.75374937779581, "epoch": 55, "n_parameters": 385301632}
{"train_lr": 0.0004346243150924412, "train_loss": 4.3803690224257865, "test_loss": 0.3879999499312127, "test_acc1": 93.78787326806953, "test_acc5": 98.79594885075778, "epoch": 56, "n_parameters": 385301632}
{"train_lr": 0.00041829019395168325, "train_loss": 4.360854209921228, "test_loss": 0.3841027860220727, "test_acc1": 93.99613829313509, "test_acc5": 98.8402734770344, "epoch": 57, "n_parameters": 385301632}
{"train_lr": 0.000402045968026835, "train_loss": 4.337777603936124, "test_loss": 0.36906941963262746, "test_acc1": 94.26512198412453, "test_acc5": 98.88854481660961, "epoch": 58, "n_parameters": 385301632}
{"train_lr": 0.0003859094001404672, "train_loss": 4.321896351423316, "test_loss": 0.3772357554690914, "test_acc1": 94.53896316826558, "test_acc5": 98.96899704923496, "epoch": 59, "n_parameters": 385301632}
{"train_lr": 0.0003698981353926441, "train_loss": 4.296675243459771, "test_loss": 0.37486856508487726, "test_acc1": 94.56598297497243, "test_acc5": 98.94349520945939, "epoch": 60, "n_parameters": 385301632}
{"train_lr": 0.000354029681866285, "train_loss": 4.276142085886154, "test_loss": 0.3656613949401175, "test_acc1": 94.85196789220097, "test_acc5": 98.98994498888848, "epoch": 61, "n_parameters": 385301632}
{"train_lr": 0.00033832139148235574, "train_loss": 4.2551919231702415, "test_loss": 0.34217624356007753, "test_acc1": 95.06721556347799, "test_acc5": 99.05612833513487, "epoch": 62, "n_parameters": 385301632}
{"train_lr": 0.0003227904410257562, "train_loss": 4.236169442408172, "test_loss": 0.3290950492517943, "test_acc1": 95.13522046987049, "test_acc5": 99.03730554863385, "epoch": 63, "n_parameters": 385301632}
{"train_lr": 0.0003074538133627917, "train_loss": 4.2148104695526145, "test_loss": 0.33173007866050747, "test_acc1": 95.33103816798516, "test_acc5": 99.09013078816899, "epoch": 64, "n_parameters": 385301632}
{"train_lr": 0.00029232827887063894, "train_loss": 4.195348392567589, "test_loss": 0.33408120783478623, "test_acc1": 95.61277277900136, "test_acc5": 99.11957934124317, "epoch": 65, "n_parameters": 385301632}
{"train_lr": 0.00027743037709919253, "train_loss": 4.167352669862303, "test_loss": 0.3245086527886137, "test_acc1": 95.72176278454678, "test_acc5": 99.13536619443758, "epoch": 66, "n_parameters": 385301632}
{"train_lr": 0.00026277639868531425, "train_loss": 4.150092105570563, "test_loss": 0.31244546998431144, "test_acc1": 95.90088284972984, "test_acc5": 99.16177881420515, "epoch": 67, "n_parameters": 385301632}
{"train_lr": 0.00024838236753925295, "train_loss": 4.131952447504925, "test_loss": 0.3024508094417963, "test_acc1": 96.10975506113245, "test_acc5": 99.21005015361823, "epoch": 68, "n_parameters": 385301632}
{"train_lr": 0.00023426402332273099, "train_loss": 4.106472468626331, "test_loss": 0.30300879607551673, "test_acc1": 96.24667565335352, "test_acc5": 99.22128310717699, "epoch": 69, "n_parameters": 385301632}
{"train_lr": 0.00022043680423786702, "train_loss": 4.091341718119638, "test_loss": 0.29805573878741787, "test_acc1": 96.4045441853671, "test_acc5": 99.23433762007116, "epoch": 70, "n_parameters": 385301632}
{"train_lr": 0.0002069158301457272, "train_loss": 4.066787970733016, "test_loss": 0.29476805412439916, "test_acc1": 96.48924672455223, "test_acc5": 99.22249748017535, "epoch": 71, "n_parameters": 385301632}
{"train_lr": 0.0001937158860329602, "train_loss": 4.045808216381626, "test_loss": 0.2969190638335805, "test_acc1": 96.61341639679287, "test_acc5": 99.25346399990285, "epoch": 72, "n_parameters": 385301632}
{"train_lr": 0.00018085140584465795, "train_loss": 4.0270679952872035, "test_loss": 0.2779351667469916, "test_acc1": 96.70419080249859, "test_acc5": 99.25953586651609, "epoch": 73, "n_parameters": 385301632}
{"train_lr": 0.0001683364567010317, "train_loss": 3.9981078136276134, "test_loss": 0.2884515959150053, "test_acc1": 96.86388089465828, "test_acc5": 99.26591132645999, "epoch": 74, "n_parameters": 385301632}
{"train_lr": 0.00015618472351522873, "train_loss": 3.9781358463737533, "test_loss": 0.27863870493462706, "test_acc1": 96.9646738806001, "test_acc5": 99.24799931995094, "epoch": 75, "n_parameters": 385301632}
{"train_lr": 0.00014440949402907236, "train_loss": 3.9525647561852884, "test_loss": 0.2778119974991809, "test_acc1": 97.05605547305979, "test_acc5": 99.24010589335373, "epoch": 76, "n_parameters": 385301632}
{"train_lr": 0.0001330236442831303, "train_loss": 3.931180302709033, "test_loss": 0.26877501004150467, "test_acc1": 97.19267247176491, "test_acc5": 99.28169817965438, "epoch": 77, "n_parameters": 385301632}
{"train_lr": 0.00012203962453692868, "train_loss": 3.915344211711843, "test_loss": 0.27382390711329174, "test_acc1": 97.24519411773777, "test_acc5": 99.26439335980668, "epoch": 78, "n_parameters": 385301632}
{"train_lr": 0.00011146944565479624, "train_loss": 3.888729555701833, "test_loss": 0.26494926662295015, "test_acc1": 97.32716431717856, "test_acc5": 99.23706996004712, "epoch": 79, "n_parameters": 385301632}
{"train_lr": 0.00010132466597215367, "train_loss": 3.873666253339388, "test_loss": 0.2655458761206897, "test_acc1": 97.41368841641714, "test_acc5": 99.25012447326557, "epoch": 80, "n_parameters": 385301632}
{"train_lr": 9.161637865663542e-05, "train_loss": 3.8513741428275896, "test_loss": 0.26648566738225477, "test_acc1": 97.47896098234727, "test_acc5": 99.24799931995094, "epoch": 81, "n_parameters": 385301632}
{"train_lr": 8.235519957788903e-05, "train_loss": 3.831400191637399, "test_loss": 0.25139986527265973, "test_acc1": 97.54818026173815, "test_acc5": 99.2300873134419, "epoch": 82, "n_parameters": 385301632}
{"train_lr": 7.355125569926154e-05, "train_loss": 3.8092224845708413, "test_loss": 0.2542031523066037, "test_acc1": 97.60404143457991, "test_acc5": 99.23524840006314, "epoch": 83, "n_parameters": 385301632}
{"train_lr": 6.521417400413113e-05, "train_loss": 3.7917249209141213, "test_loss": 0.2473036389097444, "test_acc1": 97.63106124084666, "test_acc5": 99.20185313369036, "epoch": 84, "n_parameters": 385301632}
{"train_lr": 5.735307096892422e-05, "train_loss": 3.778577934539203, "test_loss": 0.2594936434693328, "test_acc1": 97.65838464076835, "test_acc5": 99.17817285389874, "epoch": 85, "n_parameters": 385301632}
{"train_lr": 4.997654259439483e-05, "train_loss": 3.7561753679373826, "test_loss": 0.2538669047314202, "test_acc1": 97.67842180042989, "test_acc5": 99.15965366072838, "epoch": 86, "n_parameters": 385301632}
{"train_lr": 4.3092655006020885e-05, "train_loss": 3.739255887319426, "test_loss": 0.259738716484274, "test_acc1": 97.70817394683473, "test_acc5": 99.14113446755802, "epoch": 87, "n_parameters": 385301632}
{"train_lr": 3.670893563381022e-05, "train_loss": 3.726736675812869, "test_loss": 0.26071565130055413, "test_acc1": 97.72153205338385, "test_acc5": 99.10106014791067, "epoch": 88, "n_parameters": 385301632}
{"train_lr": 3.083236498117201e-05, "train_loss": 3.7120553157776377, "test_loss": 0.25870134303000375, "test_acc1": 97.73640812674842, "test_acc5": 99.10288170789464, "epoch": 89, "n_parameters": 385301632}
{"train_lr": 2.546936899183594e-05, "train_loss": 3.6975331784214966, "test_loss": 0.26283065161270486, "test_acc1": 97.75310575993481, "test_acc5": 99.07191518816714, "epoch": 90, "n_parameters": 385301632}
{"train_lr": 1.6306990433631552e-05, "train_loss": 3.6792408469364433, "test_loss": 0.2637411446731014, "test_acc1": 97.75310575977267, "test_acc5": 99.04793131504488, "epoch": 92, "n_parameters": 385301632}
{"train_lr": 1.2517626791195351e-05, "train_loss": 3.6690955944678296, "test_loss": 0.26264768987155945, "test_acc1": 97.75037341995885, "test_acc5": 99.02576900190657, "epoch": 93, "n_parameters": 385301632}
{"train_lr": 9.261864709377933e-06, "train_loss": 3.6628952524117144, "test_loss": 0.2625301814180015, "test_acc1": 97.74733748665223, "test_acc5": 99.01544682866407, "epoch": 94, "n_parameters": 385301632}
{"train_lr": 6.543264316215081e-06, "train_loss": 3.660275621999732, "test_loss": 0.2643344729774065, "test_acc1": 97.7540165399268, "test_acc5": 98.99814200881634, "epoch": 95, "n_parameters": 385301632}
{"train_lr": 4.3647983613229715e-06, "train_loss": 3.6521848994684682, "test_loss": 0.2668072569054474, "test_acc1": 97.75249857327348, "test_acc5": 98.99085576888046, "epoch": 96, "n_parameters": 385301632}
{"train_lr": 2.728848965239077e-06, "train_loss": 3.6503449324532493, "test_loss": 0.2669806522262958, "test_acc1": 97.75340935326547, "test_acc5": 98.98356952894459, "epoch": 97, "n_parameters": 385301632}
{"train_lr": 1.6372050146092782e-06, "train_loss": 3.6472953469641456, "test_loss": 0.2678970430681674, "test_acc1": 97.75006982646605, "test_acc5": 98.97415813569407, "epoch": 98, "n_parameters": 385301632}
{"train_lr": 1.0910602060662849e-06, "train_loss": 3.6486145883694143, "test_loss": 0.26965359514021975, "test_acc1": 97.74976623313539, "test_acc5": 98.97021142239548, "epoch": 99, "n_parameters": 385301632}

**Comment by huytuong010101** [comment]
Thank you so much
